services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel:latest
    container_name: syseyeid-laravel
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www
    depends_on:
      - postgres
    networks:
      - syseyeid-network

  flask:
    container_name: syseyeid-flask
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./api:/api
    networks:
      - syseyeid-network

  nginx:
    image: nginx:latest
    container_name: syseyeid-nginx
    ports:
      - "8989:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
      - flask
    networks:
      - syseyeid-network

  postgres:
    image: postgres:15
    container_name: syseyeid-postgres
    restart: always
    environment:
      POSTGRES_DB: syseyeidDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - syseyeid-network

  node:
    image: node:20
    container_name: syseyeid-node
    networks:
      - syseyeid-network

volumes:
  postgres-data:

networks:
  syseyeid-network:
    driver: bridge